### ISSUE TITLE
一份祝福，也是一份请求

### ISSUE THREAD

**Issue by sleeplessai** [pengsida/learning_research#1]
@pengsida 思达博士你好，非常感谢你的经验分享，从中学到了很多3D视觉的研究经验，最大的帮助来源于科研节奏方面的经验，也很惊喜和你研究实验习惯高度对齐。一直以来都follow你的研究动态，很多工作给了我很大的启发，能作为你的后辈真的非常幸运。

此外，我还想借你所在CADCG实验室之便，寻求一份图形学研究，特别是传统图形学中渲染、仿真等相关的科研经验。

现在大多同学用的是深度学习这一套实验方法，且相关的模型代码、开源资源特别丰富，甚至坊间流传着对着某某库做修改就能毕业的传说。
然而图形学算法大多不做开源，实验的实现和对比需要花大量时间，结果的呈现上也非常精美，这一套工作流程我相信与深度学习的研究路线有非常大的差异，很多图形学研究者分享了他们的学习路线，但却从未告诉一个图形学研究者读完论文需要准备怎样的代码库来继续做下去，这对想在CAD&CG领域的作出贡献新同学来说无疑是巨大的打击。

因此，如果不介意的话，我希望能请求一份给这些想做图形学、不想做深度学习孩子的Top PhD Student经验，这将对他们非常有帮助。
正直毕业季，如果可能，也欢迎你邀请CADCG实验室图形学方向的top同行们来分享。

最后，祝你毕业快乐！工作顺心！:D

**Comment by pengsida** [comment]
感谢你的祝福。我没有做过传统图形学方面的研究，更多的是做neural reconstruction和neural rendering，所以无法给出相应的研究经验。

**Comment by AlexanderInUM** [comment]
我感觉这份经验写的也太浅显了，好多都是一些没用的废话。希望博士能写得更系统化、深入化。
