### ISSUE TITLE
后续可否有学位论文的中文写作技巧分享系列

### ISSUE THREAD

**Issue by zhangzw12319** [pengsida/learning_research#10]
您好！首先非常感谢您的系统梳理和非常适用的方法论分享，让我们在实操如何做project, 如何开展研究，如何写小论文和有影响力的研究工作有了非常好的实操指南。
不过由于CS学科大多小论文为英语，反而很多研究生对于中文的学术写作语言表达能力可能有欠缺，比如硕博学位论文机翻痕迹偏重，如何将小论文系统性的串成大论文并且有紧密的逻辑关系，如何将自己的roadmap最后呈现为系统性的研究成果。希望后续若有经历能否将大论文写作方法也开一个系列~

此外，若有精力，非常希望能继续搜集推进，比如基金课题的写作技巧等系列，非常期待。

**Comment by pengsida** [comment]
你好，我有在整理相关内容，但因为自己经验不是很丰富，所以暂时不打算开源这些文档。

**Comment by zhangzw12319** [comment]
好的，非常期待您长期的更新！
