### ISSUE TITLE
关于链接的可访问性

### ISSUE THREAD

**Issue by WAYSC** [pengsida/learning_research#11]
思达学长好~ 
在《如何培养想idea的能力》这一篇中有一个Notion链接好像不是可访问的：
https://www.notion.so/pengsida/434a6b3e34d0403ca178fb0db2338232
![image](https://github.com/pengsida/learning_research/assets/50772845/957dfd9c-8c4e-4b66-88a8-a5bd76d7bf78)
<img width="638" alt="image" src="https://github.com/pengsida/learning_research/assets/50772845/eb8c56e6-86af-4537-9a35-f5afc8c271f7">
不知思达学长可否查看一下权限呢？或者需要我们这边申请呀~

**Comment by pengsida** [comment]
已经公开的链接都已经去敏了。这个文档里举的例子是为了说明论文要有技术贡献，不能纯靠story或者application。
