### ISSUE TITLE
彭老师，请教关于Conclusion如何写的问题

### ISSUE THREAD

**Issue by weiaicunzai** [pengsida/learning_research#12]
彭老师，感谢您分享出来这么好的科研经验，看完后受益匪浅。
不过在[论文写作模板](https://pengsida.notion.site/c1a22465a0fa4b15a12985223916048e)中，关于Conclusion部分我有点不明白。

关于Conclusion，您是这么写的：`Limitation一般写的是因为task goal或者task setting而导致的limitation（类似于讨论future work），不要写技术上存在的缺陷。`，
然后您举了一个例子如下:
```Common videos are more than a few minutes. However, this work only deals with videos of 100 to 300 frames, which are relatively short, thus limiting the applications. How to model a long volumetric video remains an interesting problem.```

对于您举的例子，在我看来，```this work only deals with videos of 100 to 300 frames,``` 同样也算技术上的缺陷，即该方法无法处理长序列。
我想知道 `技术上的缺陷`和 `因为task goal或者task setting而导致的limitation` 之间的本质区别是什么？比如我提出的算法虽然显存消耗比当前方法更小，但是训练时间却更长，这个算技术上的缺陷还是task goal导致的缺陷呢？

**Comment by pengsida** [comment]
“技术上的缺陷”和“因为task goal或者task setting而导致的limitation”之间的区别确实比较模糊。
一般来说，一篇论文要提升一个metric并且不明显损害其他metrics。
你举的例子里，“提出的算法虽然显存消耗比当前方法更小，但是训练时间却更长”，如果损害了已有的metrics，那么可能被人当作一个严重的limitation。
我举的例子里，“this work only deals with videos of 100 to 300 frames”，因为目前SOTA方法基本只能处理比较短的视频，所以确实是future work了。

**Comment by pengsida** [comment]
是常用的evaluation metrics。
一个任务它常用的evaluate metric如果只有一个Acc，那么方法训练时间更长不会被人当作一个严重的limintation。

**Comment by weiaicunzai** [comment]
好的，谢谢老师。
请问Conclusion里limitation的写法只有 `task goal` 或者`技术上的缺陷` 两种嘛？

我看到一篇从难样本挖掘的角度做病理图像分类任务的一篇2023 ICCV (Oral) 的[文章](https://openaccess.thecvf.com/content/ICCV2023/papers/Tang_Multiple_Instance_Learning_Framework_with_Masked_Hard_Instance_Mining_for_ICCV_2023_paper.pdf)。该工作提出了三种难样本挖掘的方法，在Conclusion中写道要设计更多的难样本挖掘方式。
`In future work, we plan to devise a more precise localization scheme for hard instances that can facilitate model training and convergence.`

这种是什么写法呢？这种写法好像既不属于您说的'task goal'，也不属于技术缺陷。
病理图像分类任务主要的Metrcs是Acc，AUC，F1。

**Comment by pengsida** [comment]
这是future work，不属于limitation。Conclusion不只有limitation，也可以讲summary。

**Comment by weiaicunzai** [comment]
好的，谢谢老师。

**Comment by LiHaodong0217** [comment]
谢谢彭老师
总结一下就是别涉及到experiment matric且听起来像是未来发展趋势的内容可以写到limitation里面比较保险
