### ISSUE TITLE
科研绘图工具

### ISSUE THREAD

**Issue by xiaoyaocoding** [pengsida/learning_research#13]
非常感谢彭老师的科研经验分享，为像我一样对科研感兴趣但苦于无人引导的学生指明方向。
想问下彭老师，关于3D Vision的绘图
1. 除了PPT以外，有什么开源的容易上手的工具可以高效地画出好看的图呢？
2. 呈现实验效果的图片是否有什么比较好用的工具？
感激不尽！

**Comment by pengsida** [comment]
你好，我一般用adobe illustrator画图。
如果是中间元素/实验效果的可视化，一般可以用一些代码工具
1. https://github.com/zju3dv/Wis3D
2. https://github.com/koide3/iridescence
3. https://github.com/nerfstudio-project/viser

**Comment by xiaoyaocoding** [comment]
好的，谢谢老师，我把问题关闭了
