### ISSUE TITLE
关于技术贡献

### ISSUE THREAD

**Issue by clearloveclearlove** [pengsida/learning_research#14]
彭老师，您好，读完您的科研分享经验收益匪浅。尤其是读到您的这句"不能期望论文story好听、application有意思，reviewer就会放过我们的技术贡献"更是感同身受，我最近正卡在一直被reviewer质疑技术贡献的阶段。

我目前对科研粗浅的理解是创造出新的知识，为所从事领域提供足够大的信息量，因此我最近做了一些论文也是基于这个准则，也就是重点为所从事的领域提供有意思的insight，比如提出以前方法没有关注到的一个新的维度。但是从技术角度，我的方法每次都是基于这个insight设计出来的比较直观粗暴的方法(由于insight带来的一些从理论上的优势，实验效果在所提出新的维度上自然会更好)，这造成了我的工作总是会被一些审稿人质疑"虽然观点/视角有意思，但是方法trival，没有技术贡献" 。

最近饱受这方面的困扰，因此想向您请教一下提高自己工作的技术贡献呢。

**Comment by pengsida** [comment]
很多时候insight在审稿人眼里只是个story。可能从改进pipeline的角度做论文可以让人觉得有更多的技术贡献。

**Comment by pengsida** [comment]
没有技术贡献的论文经常被reviewer叫成straightforward pipeline，具体定义为：
1. 第一种情况，把一个已有的方法直接用在某个新任务/新数据上，没改其中的module。
2. 第二种情况，把几个已有的modules直接拼接，而且拼接方式很简单，没带来新的知识，也没对这些modules进行修改。

**Comment by clearloveclearlove** [comment]
> 很多时候insight在审稿人眼里只是个story。可能从改进pipeline的角度做论文可以让人觉得有更多的技术贡献。

非常感谢，您的回复以及您发布的内容对我受益匪浅！
