### ISSUE TITLE
关于三维计算机视觉的学习

### ISSUE THREAD

**Issue by leyangjin** [pengsida/learning_research#15]
首先非常感谢彭老师的经验分享。因为最近的项目需要，加上学校开设三维视觉的课程较少，需要自己补三维计算机视觉的知识。网络上，包括彭老师也推荐了很多优秀的三维视觉课程，比如[图宾根大学的视觉课程](https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/lehrstuehle/autonomous-vision/lectures/computer-vision/)。但是这些课程大多为课程视频本身，缺少作业的部分以及测评代码。想请教一下彭老师在这种自学的情况下，如何寻找合适的代码练习让自己对课程的内容有更深的了解。多谢彭老师！

**Comment by pengsida** [comment]
https://github.com/PLUS-WAVE/3D_CV-Course-Exercise/ 这里是图宾根大学的视觉课程作业。

**Comment by leyangjin** [comment]
非常谢谢彭老师！
