### ISSUE TITLE
关于怎么审论文

### ISSUE THREAD

**Issue by DachunKai** [pengsida/learning_research#16]
彭老师您好，非常感谢您的这份经验总结，我受益匪浅！

您在”怎么审论文“中写道论文被拒的原因时，一个常见的被拒的原因有contribution不够，比如想解决的failure cases很常见。**我有一个疑问是，想解决的failure cases很常见不正是说明这个问题很重要吗，即大家都还没有解决好它，我们去解决这个常见的问题不是很有意义吗。是不是我理解有误呢？**

期待彭老师回复！

**Comment by pengsida** [comment]
你好，你说的对，如果大家都在解决某个failure case并且还没解决好，那么这个failure case很重要。
我表达的不够清楚，想说的是大家都在解决某个failure case并且已经解决得挺好的了，只是还一直有人在做marginal improvement。

**Comment by DachunKai** [comment]
明白了，谢谢彭老师！
