### ISSUE TITLE
请教老师关于论文写作模板中方法部分的问题。

### ISSUE THREAD

**Issue by weiaicunzai** [pengsida/learning_research#17]
老师好，感谢分享这么好的模板。

我想请教一下，您在[论文写作模板](https://pengsida.notion.site/c1a22465a0fa4b15a12985223916048e)中提到了两个概念。module design 和 Module forward process。这两个概念的核心区别是什么呢？您给的Neural Body 的[例子中](https://pengsida.notion.site/image/https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2F952f5f87-b692-4249-a557-7f7ad0a77d56%2Ff79b3a78-0c06-4c20-95fe-2526655d0ade%2FUntitled.png?table=block&id=5684358c-52e3-45a6-960a-0cdadad927ef&spaceId=952f5f87-b692-4249-a557-7f7ad0a77d56&width=2000&userId=&cache=v2)，我没有找到您的module design模块的具体写作规律。 Module forward process的写作规律倒是挺明确的， 从输入到输出。

**Comment by pengsida** [comment]
Module design指的是对某个模块的设计，比如Instant NGP或3DGS的数据结构的设计。

**Comment by pengsida** [comment]
好问题。我需要想一下。目前看起来好像通过描述一个模块的forward process能比较清楚地介绍一个模块的设计细节。

**Comment by pengsida** [comment]
再次感谢你的交流，我把method写作部分更新了：
<img width="740" alt="image" src="https://github.com/pengsida/learning_research/assets/11582122/9e554892-8762-4731-886c-722caa3c8a86">

**Comment by weiaicunzai** [comment]
好的，谢谢老师。我最近看了您推荐的那本"writing science how to write papers that get cited and proposals that get funded"。我感觉现在的版本更符合书中描写的一个论文的arc。

**Comment by pengsida** [comment]
嗯嗯，和你交流很有收获。
