### ISSUE TITLE
请教老师关于论文写作模板中方法部分的问题。

### ISSUE THREAD

**Issue by weiaicunzai** [pengsida/learning_research#18]
彭老师好，谢谢您的分享。您在方法部分，推荐了四种方式：

版本1，先写module forward process，然后写module discussion。
版本2，先写module discussion，然后写module forward process。
版本3，先写module design，然后写module discussion。
版本4，先写module discussion，然后写module design。

您这四个版本里，通常是motivation或者advantage合并成一个部分，其余的方法描述是另一部分。这两部分顺序变换着写。

但是我个人的经验，先写motivation，然后写forward process，最后总结方法的advantage。
因为我感觉，如果我在最开始不介绍为啥要用方法A，会让读者有点突兀。
如果在介绍完方法A怎么做的之前就开始说advantage，也会让读者疑惑：为什么方法A可以做到这种advantage。

所以我想请教一下：motivation，然后写forward process，最后总结方法的advantage这种三段式的写法相比您推荐的四种写法，有什么优劣嘛？

**Comment by pengsida** [comment]
你说的对，我最近写method，一般顺序是：motivation/insight/observation、具体做法、具体的技术优势。
我会更新论文写作模板里的method部分。
感谢你的交流。

**Comment by weiaicunzai** [comment]
> 你说的对，我最近写method，一般顺序是：motivation/insight/observation、具体做法、具体的技术优势。 我会更新论文写作模板里的method部分。 感谢你的交流。

不客气，彭老师，感谢您的分享，我也很高兴能与您交流。
