### ISSUE TITLE
请问个人主页有模版吗？

### ISSUE THREAD

**Issue by liushunyu** [pengsida/learning_research#19]
彭老师你好，看到你的个人主页风格设计非常简洁大气（ https://pengsida.net/ ），尤其是 Research Summary 部分很高级。可以请问一下是否是基于哪个开源主页模版设计的吗，还是自己搭建的哇？

**Comment by pengsida** [comment]
你好，Research Summary是我看到其他人主页的启发，自己设计实现的。

**Comment by liushunyu** [comment]
好的谢谢~
