### ISSUE TITLE
关于链接的可访问性

### ISSUE THREAD

**Issue by Haoran-P** [pengsida/learning_research#20]
彭老师您好，非常感谢您分享的科研经验文档。我学习后得到了很多启发！

在文档中有一个我非常感兴趣的题目，一直无法访问，想请老师帮忙解决：
![1716804250072](https://github.com/pengsida/learning_research/assets/85212359/840dcb34-3b79-4a54-ad54-bfe42e17373c)

谢谢老师🙏

**Comment by pengsida** [comment]
你好，请参考下面这两个链接：
https://github.com/pengsida/learning_research/issues/11
https://github.com/pengsida/learning_research/issues/14

**Comment by Haoran-P** [comment]
谢谢老师🙏
