### ISSUE TITLE
关于方法驱动类的工作怎么想motivation。

### ISSUE THREAD

**Issue by weiaicunzai** [pengsida/learning_research#21]
感谢彭老师分享的[如何培养想idea的能力](https://pengsida.notion.site/idea-da6ce171c13846b7a7ffaa7473ffa6ea) 这篇文章。这篇文章提到了我们要从问题出发去做科研，而不是基于现有的方法去改进 （"methods-driven tinkering".）。

当然我们应该从问题的角度做科研，但是有时候，基于现有的方法改进，也能产生一个SOTA的metric。从功利的角度讲，不太想浪费这一篇文章。但是这类工作确实不太好想故事，因此想请教一下，"methods-driven tinkering"方式做科研，写故事的角度，有没有一个系统性的方法，类似一个算法一样，做了第一步，第二步，第三步，故事自然而然就会输出出来。

拿我自己举例子，我在跑一个baseline的时候，突发奇想把某个顶会文章提出的模块删除了，结果反而高了不少。因此，我也不想浪费这个点，想发出来，毕竟现在这么卷。于是在想文章的motivation，把该领域里面遇到的主要问题一个一个套到我的方法里，但是感觉motivation都有点瑕疵，不是很站住脚。

所以我的问题就是，对于基于方法的创新，如何想方法的motivation？假如何恺明有一天无意间加了一下 shortcut connection，发现效果很好，他有什么系统性的步骤得到 故事 ”shortcut connection可以解决网络退化问题“ ？

**Comment by pengsida** [comment]
如果是这种情况，需要想清楚为什么这个方法能work。

**Comment by weiaicunzai** [comment]
好的，谢谢老师
