### ISSUE TITLE
关于文献树的构建问题

### ISSUE THREAD

**Issue by weiaicunzai** [pengsida/learning_research#22]
彭老师好。感谢您分享关于[文献树](https://pengsida.notion.site/literature-tree-literature-review-novelty-tree-challenge-insight-tree-f8b36e484b344a2893a94e4608b72ec2)构建的经验。 关于这个文章，我还有一个问题想问。

四类novelty应该如何划分？

比如拿图像分类任务来举例子。我的理解是：
第一类 （第一个工作）:   AlexNet。
第二类 （新的范式）:  ViT，Mamba。 
第三类 （新的模块）：VGG, ResNet，MobileNet, GoogleNet， Swin transformer， MLP-Mixer。 
第四类（搞不懂和第三类的区别）:DenseNet，ResNext , MobileNetv2, 

其中，第三类和第四类的区别我个人不太明白，感觉第四类里的网络也可以放在第三类（新的模块），希望彭老师能指正。谢谢。

**Comment by pengsida** [comment]
你举的这些工作都很好啊。每个人都有自己评价的方式吧。
因为我对网络架构的工作不熟悉，所以我难以给出分类。
