### ISSUE TITLE
请问一下，novelty tree指的是什么？

### ISSUE THREAD

**Issue by weiaicunzai** [pengsida/learning_research#23]
感谢彭老师的分享。在 [如何构建literature tree](https://pengsida.notion.site/literature-tree-literature-review-novelty-tree-challenge-insight-tree-f8b36e484b344a2893a94e4608b72ec2) 这篇文章中的标题中，您提到“构建novelty tree和challenge-insight tree”。 但是正文中的标题是“如何创建literature tree：” 和 “如何创建challenge-insight tree：”，以及给出的[示例图中](https://alidocs.dingtalk.com/i/nodes/QOG9lyrgJPwBpdn0u1B3aO2PVzN67Mw4) 只有literature  tree和challenge-insight tree。 

请问您在这篇文章中提到的literature tree指的就是novelty tree嘛？

**Comment by pengsida** [comment]
是的。
