### ISSUE TITLE
请问文献树的general goal， milestone task，　subtask　是如何确定的呢

### ISSUE THREAD

**Issue by weiaicunzai** [pengsida/learning_research#24]
感谢老师分享的文献树　[示意图](https://alidocs.dingtalk.com/i/nodes/QOG9lyrgJPwBpdn0u1B3aO2PVzN67Mw4)。

关于文献树，请问general goal，  milestone task，　subtask　是如何确定的呢？

比如拿自然图像分类任务来说，我认为：
（１）general goal是 “预测一个自然图像的标签”（类似论文投稿的大track）
（２）milestone task就是“全监督图像分类”，＂半监督图像分类等＂，（类似论文投稿的小track），
（３）subtask　我就不能确定是什么了。比如对于 milestone task 全监督图像分类任务，我想不出来有什么sub task，感觉就已经是最基础的task了。
（４）对于利用数据增强来增加训练样本的任务来说（如mixup），是应该另外开一个general goal，还是应该划分到一个milestone task里呢？

**Comment by pengsida** [comment]
subtask可以定义成图像难度、类别数量。
“利用数据增强来增加训练样本” 这个应该是一种技术吧。

**Comment by weiaicunzai** [comment]
> subtask可以定义成图像难度、类别数量。 “利用数据增强来增加训练样本” 这个应该是一种技术吧。

谢谢老师回复。subtask按照您的意思，可以是例如细粒度图像分类（类别之间非常相似的图像），或者说小样本图像分类 这种的任务嘛？

**Comment by pengsida** [comment]
subtask我更倾向于定义为完成该milestone task的一些指标、难点。

**Comment by weiaicunzai** [comment]
> subtask我更倾向于定义为完成该milestone task的一些指标、难点。

谢谢老师，我大概明白您的意思了。  我注意到您是使用方法来进行分类的，那如果我就想调研某一类方法的文献该如何做呢？

比如说我想调研所有Transformer在图像分类领域的文章，这个时候要以什么为标准来构建文献树呢？还是任务嘛？

**Comment by weiaicunzai** [comment]
> > subtask我更倾向于定义为完成该milestone task的一些指标、难点。
> 
> 谢谢老师，我大概明白您的意思了。 我注意到您是使用任务来进行构造文献树的，那如果我就想调研某一类方法的文献该如何构建文献树呢？
> 
> 比如说我主要研究方向是模型结构，想调研所有使用大卷积核网络[1] 的相关文章，这个时候要以什么为标准来构建文献树呢？还是任务嘛？ 因为同一类网络架构可能会用在不同的任务上，这样general goal, milestone task, subtask应该是什么呢。
> 
> [1] Xiaohan Ding, Xiangyu Zhang, Yizhuang Zhou, Jungong Han, Guiguang Ding, Jian Sun. Scaling Up Your Kernels to 31x31: Revisiting Large Kernel Design in CNNs. 2022. CVPR.

**Comment by weiaicunzai** [comment]
> > subtask我更倾向于定义为完成该milestone task的一些指标、难点。
> 
> 谢谢老师，我大概明白您的意思了。 我注意到您是使用任务来进行构造文献树的，那如果我以方法为标准构建文献树呢？
> 
> 假如我的主要研究方向是模型结构，现在想调研所有使用大卷积核网络[1] 的相关文章，看该模型进展如何。因为同一类网络架构可能会用在不同的任务上，这样文献树中的general goal, milestone task, subtask应该如何定义呢。
> 
> [1] Xiaohan Ding, Xiangyu Zhang, Yizhuang Zhou, Jungong Han, Guiguang Ding, Jian Sun. Scaling Up Your Kernels to 31x31: Revisiting Large Kernel Design in CNNs. 2022. CVPR.

**Comment by pengsida** [comment]
我不清楚模型结构方面的研究。
general goal是模型结构设计领域的终极目标，milestone task指的是重要的指标，subtask指的是某个指标下面的一些细分情况。

**Comment by weiaicunzai** [comment]
> 我不清楚模型结构方面的研究。 general goal是模型结构设计领域的终极目标，milestone task指的是重要的指标，subtask指的是某个指标下面的一些细分情况。

好的，谢谢老师。
