### ISSUE TITLE
老师好，请问一下文献树的问题

### ISSUE THREAD

**Issue by weiaicunzai** [pengsida/learning_research#25]
老师好，感谢您对于文献树的分享。

请教一下，我的这种文献树的构造方法有什么缺点嘛？

第一层（相当于您的general goal那一层）：某个目标（比如说全监督条件下的图像分类，或者所有的）
第二层 （相当于您的milestone task 那一层）：该任务使用的技术路线（CNN-based,  Transformer-based，GNN-based）等
第三层（相当于您的sub task那一层）：每类技术下的工作介绍。比如CNN-based技术路线就写上resnet，densenet等，每个工作写上解决的挑战，用的什么方法的大致描述。

**Comment by pengsida** [comment]
我觉得挺好的呀。只要方便自己记忆和总结，就是好的文献整理方法。
