### ISSUE TITLE
关于发现 failure cases

### ISSUE THREAD

**Issue by whuhxb** [pengsida/learning_research#26]
您好, 非常感谢您详细细致的总结跟分享！感觉很实用！

想请问一下，关于发现新的 failure cases，有什么好的建议吗？只是关于已有的实验结果是不太容易发现的。发现 failure cases 的过程需要结合武器库这些吗？或者，您有什么好的实践经验吗？怎样才能知道自己发现的 failure cases 是具有较强创新性的呢？

**Comment by pengsida** [comment]
在一些新数据、新setting上跑实验，应该挺容易发现的。

“怎样才能知道自己发现的 failure cases 是具有较强创新性的”，这个需要经验的积累。如果是初学者，建议找有经验的人判断。
