### ISSUE TITLE
请教一下关于论文动机的问题

### ISSUE THREAD

**Issue by weiaicunzai** [pengsida/learning_research#28]
老师好，感谢您分享的科研经验。 我最近对于论文动机部分，有一个问题想请教。就是我看到有一些论文的动机，会直接说 “然而，XXX放在A任务上还没有被探索过。”   

请问这种动机，要在什么条件下写才合适呢？如果这样子的动机随便都能写，那么我可以把随便任何一个技术拿到某个领域去发文章，甚至不需要想动机，直接写“该类技术在XX任务上还未被探索过”就行了。

**Comment by pengsida** [comment]
如果能做到SOTA效果，那么这样一般是没问题的。

**Comment by weiaicunzai** [comment]
> 如果能做到SOTA效果，那么这样一般是没问题的。

是否要是热点的技术才行呢？比如说22年左右，mlp-mixer比较火，我看到有拿到不同领域应用的，动机就是研究mlp-mixer在不同领域的应用。
但是现在24年了，mlp-mixer已经不火了，再这么说会被审稿人质疑嘛？（虽然确实是第一个拿来在这个领域用的）

**Comment by pengsida** [comment]
需要是新技术、under well-explored techniques，不一定要是热点技术。

**Comment by weiaicunzai** [comment]
> 需要是新技术、under well-explored techniques，不一定要是热点技术。

谢谢老师。请问您说的这个新技术，“新” 指的是：
（1） 被发明的绝对时间上的新。比如transformer被发明于2017年，现在即便下游任务A上没有人应用过transformer，我也不能说动机是探索transformer在下游任务A上的应用。
（2） 在该领域应用时间上的新。比如虽然transformer发明于7年前，但是只要在我这个下游任务A没有人用，我就可以说动机是探索transformer在下游任务A上的应用。

**Comment by pengsida** [comment]
被发明的绝对时间上的新。

**Comment by weiaicunzai** [comment]
> 被发明的绝对时间上的新。

谢谢老师。那请问这种文章，解决得科学问题是什么？
我感觉 “探索XX技术在XX任务上的应用 ”  反而是工程问题，不是科学问题啊？

**Comment by pengsida** [comment]
“把新技术应用到新的领域”是探索新技术新性质的过程。比如DreamFusion，把stable diffusion应用到了3D generation上。

**Comment by weiaicunzai** [comment]
> “把新技术应用到新的领域”是探索新技术新性质的过程。比如DreamFusion，把stable diffusion应用到了3D generation上。

请问什么叫做探索出新性质呢？

我的理解：
比如我在transformer刚出来的时候，用在任务A上。 
如果直接就拿来用，几乎不用任何改动就work的很好，这种不叫探索出新性质，所以就没有什么科学问题。  
如果直接拿来用，会在任务A上遇到一些任务A特有的一些问题，然后我提出改进，这种算是探索出了新的性质， 也算解决了科学问题。
请问老师，我这种理解对嘛？

**Comment by pengsida** [comment]
你理解得对，是这样子的。

**Comment by hypochlorous** [comment]
> “把新技术应用到新的领域”是探索新技术新性质的过程。比如DreamFusion，把stable diffusion应用到了3D generation上。

老师您好,那这样的开创工作如何对比评价,如何进行消融实验呢?

**Comment by pengsida** [comment]
这种工作一般会有自己设计的一些模块，需要对这些模块进行消融实验。
