### ISSUE TITLE
关于“如何培养想idea的能力”章节的“参考文档”一栏的分享与添加建议

### ISSUE THREAD

**Issue by qingfengzhumingyue** [pengsida/learning_research#29]
1.感谢：感谢彭教授的无私分享。特别是教授在不知道我是谁的情况下，第一时间在钉钉文档和notion笔记的一些内容的权限通过，感谢。
2.分享：“如何培养想idea的能力”章节的“参考文档”中“Michael_Nielsen的科研经验”一文，由于原文篇幅很长，我找了热心网友的中译文，方便看英文版时有个对比参考。
   “Michael_Nielsen的科研经验”中译版来源“https://zhuanlan.zhihu.com/p/560852116” ，且得到原文作者的认可。（备注：该中译版翻译自Michael_Nielsen的blog版本“https://michaelnielsen.org/blog/principles-of-effective-research” ，与教授上传的pdf版本相比少了很多个人经历的句子，需要读者在阅读pdf版本时加以甄别）。
3.添加建议：Richard_Hamming是一位数学家和计算机科学家，他的演讲在数学和计算机领域会有普适性帮助。偶然找到Richard_Hamming的演讲文章，建议被添加在“参考文档”一栏。该建议供教授参考，该文也供各位同学参考。
演讲文章：[YouAndYourResearch.pdf](https://github.com/user-attachments/files/18051592/YouAndYourResearch.pdf)

**Comment by pengsida** [comment]
我已经更新两个地方。感谢你的认可和建议。
