### ISSUE TITLE
关于确定科研目标的一些疑惑

### ISSUE THREAD

**Issue by Gaben21** [pengsida/learning_research#3]
您好，我们实验室是做基于视觉的机械臂抓取相关工作的，实验室师兄主要是做基于深度学习的方面的，老师现在希望可以从强化学习的角度去考虑机械臂抓取工作，师兄给我推荐了几篇相关的文章，包括深度强化学习的（有偏强化学习方面的也有偏深度学习方面的），也有纯强化学习的研究，但是总体上来说，这些都是比较大的分支，该如何去选择更加具体的研究目标呢？希望您能给点建议和思路

**Comment by pengsida** [comment]
好问题。首先要确定长远的科研目标，然后整理该科研目标下当前已有的论文，帮助自己构建对这个领域的认识，清楚有哪些重要的问题，然后确定哪个是接下来最值得做的问题。

**Comment by pengsida** [comment]
对于长远的科研目标，你觉得“基于视觉的机械臂抓取”的终极形态是怎样的。

**Comment by Gaben21** [comment]
我觉得简单来说终极形态应该是达到人类的抓取物体水平以及抓取的思维方式吧，大概就是在复杂环境中可以多自由度的灵活抓取，并且可以在抓取过程中保持稳定，抓取效率尽可能高，可以对特定物体进行抓取

**Comment by pengsida** [comment]
你可以先列出这个方向已有的论文。根据你说的这个终极形态和已有的论文，从这些论文中总结出一些他们在解决的问题，整理得到已有的一些milestone tasks，并根据milestone tasks对他们进行分类。然后找一个较新的milestone task去做，或者自己定义一个接下来应该解决的milestone task。

**Comment by Gaben21** [comment]
好的，感谢您的建议

**Comment by Gaben21** [comment]
顺便求问一下，在阅读论文的时候有什么比较好的记笔记方式和阅读习惯呢？以及对论文的总结的一些思路和建议。

**Comment by Gaben21** [comment]
好的，多谢

**Comment by pengsida** [comment]
@Gaben21 我写了一个《如何有效地读论文》的文档：https://pengsida.notion.site/d192db870bc64436ae4a4a590b36772a

**Comment by Gaben21** [comment]
好的，谢谢您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月16日(周日) 晚上8:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pengsida/learning_research] 关于确定科研目标的一些疑惑 (Issue #3)




 
@Gaben21 我写了一个《如何有效地读论文》的文档：https://pengsida.notion.site/d192db870bc64436ae4a4a590b36772a
