### ISSUE TITLE
关于文献调研的完备性判断

### ISSUE THREAD

**Issue by Nickisdope** [pengsida/learning_research#30]
彭老师您好！感谢您有关文献树方法的分享。 
  我最近在文献调研选题的过程中实践这一方法，但现在3DV方面的论文数量过多，我在建立文献树的过程中比较担心会遗漏一些论文  而迟迟没有推进到想idea的阶段，请问您是如何判断文献调研已经做得比较全面了呢？
  我现在的理解是找到特定问题的几篇代表性论文（kimi推荐），然后找他们引用和被引中**citation比较高**的或者是**比较新**的工作（一年内），此间结合connected paper进行文献的筛选和关系梳理。
  之后，当我想到一个idea时，我会进一步查找以确保没有相似的研究，如果没有，我就会推进到实现idea的阶段。同时，我也会通过twitter和scholar inbox来保持对新文献的追踪，以确保我的idea没有被提前实现。
  我想请教您，我目前的方法有没有可以改进之处？如何判断文献调研已经做得比较全面且可以推进到想idea阶段？感谢

**Comment by pengsida** [comment]
没必要把所有3DV的论文都看一遍。

**Comment by Nickisdope** [comment]
感谢老师的回复。

我是有一个特定的研究方向的，例如说 human pose estimation。如果说要在这个方向找一个值得做的问题，**怎么样判断我在此方向的文献调研已经完备？**

是把所有高被引论文（milestone papers）和最新的 paper （一年内）都阅览过吗？还是需要对每个 milestone paper 衍生的 follow-up works 有更详尽的收集了解？

**Comment by Nickisdope** [comment]
好的，感谢老师的提醒。

想最后确认一下我的理解：
先找到一个特定研究方向的 milestone papers （高引用，提出新问题，新的pipeline），理解这些 papers 想 idea，搜索确认自己的 idea 没有被新论文所解决，就可以接着进入动手做 project 的阶段了。是这样吗？

**Comment by pengsida** [comment]
你好，不能只通过看论文来想idea。你可以看看这个文档：https://www.notion.so/pengsida/idea-da6ce171c13846b7a7ffaa7473ffa6ea

**Comment by Nickisdope** [comment]
好的，感谢老师的回复。
