### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qingfengzhumingyue** [pengsida/learning_research#31]

**Comment by qingfengzhumingyue** [comment]
1.您的《自然科学的定义（数学与科学的区别）》一文，网址：https://pengsida.notion.site/1053fe292ff18015b2f3cde4498a5f0f 。
该文来自于“中国教育发展战略学会人才发展专业委员会”网站的《科学与数学的区别》一文，网址：https://hr.edu.cn/xueshu/202209/t20220908_2244759.shtml 。这是目前网上我能搜到的第一来源。
2.建议教授注明来源。

**Comment by pengsida** [comment]
哦，我忘记注明了，抱歉。我已经加上去了。

**Comment by qingfengzhumingyue** [comment]
给您点赞！
