### ISSUE TITLE
如何做科研日程规划

### ISSUE THREAD

**Issue by lisenjie757** [pengsida/learning_research#4]
彭博士你好，我想问你是给如何自己的科研做每日计划的，来使自己的科研进度可以按部就班、稳定持续的进行，例如每周看多少篇论文这种。
因为我导比较放养，一点也不push，我自己又属于那种执行力很弱，不会做计划的人，我总是来感觉的时候热情爆发做一点，平时总是摆烂拖着，时光总是在不知不觉中溜走许多，导致我的科研进度很慢。
所以来问问你是怎么给自己安排每日日程的，又是如何做长期规划和短期规划的，希望博士能具体说说，如果能分享下自己日程表就更好啦。

**Comment by pengsida** [comment]
我一般每天读一篇论文。我没有具体的日程表，会把要做的事情列出来，然后尽快做完。

**Comment by lisenjie757** [comment]
博士的自驱力很强，像我如果提前计划好我就不知道做什么

**Comment by lisenjie757** [comment]
博士的自驱力很强，像我如果提前计划好我就不知道做什么

**Comment by pengsida** [comment]
好吧，加油。
