### ISSUE TITLE
如何判断一个研究问题是否值得去做（是好的问题）呢？

### ISSUE THREAD

**Issue by Master-cai** [pengsida/learning_research#5]
首先非常感谢您的分享，我感觉学习到了很多东西。您在《如何培养想idea的能力》中说“选题是对一个research project影响最大的一步，而不是后面的想方法。”，我非常赞同您的看法。所以关于“选择有研究空间的task”这一点能不能多分享一下您的看法呢？

比如，如何判断一个研究问题是否还有研究空间？该方向上目前的SOTA方法在某些数据集的指标已经快到极限了是否就说明它没有研究空间？或者近期的工作指标的提升都不大是否也能说明这方面没有研究空间了呢？是不是这些情况反过来就说明有研究空间？除了实验指标是否还有其他方面能判断一个问题是否有研究空间呢？
另外，如何判断一个问题是有价值的问题呢？如果一个研究问题在该领域的顶会上发表的数量很少，是否就说明这个研究问题不是很重要呢？反之在顶会上发表过很多论文的研究问题就很值得做？
希望能听听您的看法，谢谢！

**Comment by pengsida** [comment]
理想情况下，你最好有一个自己的目标，实现一个新的AI功能，然后思考要实现这个goal还需要完成哪些sub-goals。这样子你能很自然地知道哪些任务是值得去做的。

也可以从“重要性”和“研究空间”两个角度来选择研究问题：
1. 重要的任务是比较fundamental的，有比较多的下游应用。不过重要的任务不一定是好的任务，因为这个任务可能已经被很多人研究过了，导致研究空间不够大。
2. 研究空间较大的任务一般做的人还不是很多，或者performance还有比较大的提升空间。
综合来说，推荐做重要且研究空间较大的任务。

**Comment by Master-cai** [comment]
明白了，感谢！
