### ISSUE TITLE
关于NeRF

### ISSUE THREAD

**Issue by tuning12** [pengsida/learning_research#7]
首先非常感谢思达博士的经验分享。作为一名图形小白，我想以nerf作为后续的研究方向，不知思达博士可否给出更丰富的资料和建议，在学习game101的过程中，感觉有些内容并未涉及，如三角面片的插值。
再次感谢思达博士的分享。

**Comment by pengsida** [comment]
你好，我没有上过nerf相关的课程，对这个领域的学习主要以看论文为主。但通过论文进行学习对于初学者而言是比较困难的。
我从网上找到了一个nerf相关的课程：https://www.cs.unc.edu/~ronisen/teaching/fall_2022/comp_790_neural_rendering_fall_2022.html
但我没上过这个课，不确定这个课程的质量。

**Comment by tuning12** [comment]
感谢思达博士的回复。
