### ISSUE TITLE
关于 Research 代码和可复现性

### ISSUE THREAD

**Issue by JamesSand** [pengsida/learning_research#9]
非常感谢您的分享。读完这些对我的 Research 帮助很多

实际上写代码在 CS Research 里边仍然占据了一个很大的部分。好的代码风格和实验可复现性是保证 Research 效率的很重要的因素。
但是我遇到的一些 paper 的 codebase 存在代码风格极差，变量命名混乱，结果难以复现的问题

不知道您之后会考虑继续增加类似 “如何在 Research 迭代中保证代码质量” 以及“用哪些工具可以尽可能保证实验的可复现性” 类似的文字呢？

**Comment by pengsida** [comment]
你好，根据我的经验，codebase的代码风格和可复现性与作者的代码能力有较大关系。因为算法种类很多，难以有一个统一的代码范式来约束算法实现。
一种保证代码质量的方式是在一个灵活并有规范的代码框架下实现算法。
我印象里没有特别的工具能保证实验的可复现性。可复现性主要和算法、代码质量有关。

**Comment by JamesSand** [comment]
非常感谢您的回答！
您提到了“一个灵活并有规范的代码框架” 请问这个有什么比较好的文档或者 codebase 可以作为学习参考吗

**Comment by pengsida** [comment]
https://github.com/pengsida/learning_nerf 比如这个框架，是我们实验室常用的框架。还有同学喜欢用pytorch lightning。
